### ISSUE TITLE
User Sign Up[Pre-Email]

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix-API#127]
This issue is the create a partial user and trigger a mail to be sent to the user

This issue should have a solution for following:
* Take an Email and a password and store it with encryption.
* Make a user in the DB with `verified: false`.
* Trigger an email to be sent to the user.

**Comment by NikitaMasand** [comment]
Please assign this issue to me.

**Comment by NikitaMasand** [comment]
Solved in #137

**Comment by NikitaMasand** [comment]
@abhishek71994 the pr was not reviewed or merged?
was there anything wrong?
