### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by abhishek71994** [WrippleFoss/mentorFix-API#129]
The solution to this issue should:
* check for the validity of the user.
* check if the user is verified or not.
* render different views based on the role the user has.
* returns token and extra data that can be stored in the cookies in the front end.

**Comment by NikitaMasand** [comment]
I would like to start working on this issue

**Comment by Jayashree-panda** [comment]
That's great @NikitaMasand 
We really appreciate your enthusiasm. Please carry on.

**Comment by abhishek71994** [comment]
@NikitaMasand would like to know how much progress you have made and also a PR in the next 2 days please.

**Comment by abhishek71994** [comment]
solved in #132
